#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : pdsh
Version  : 2.34
Release  : 11
URL      : https://github.com/chaos/pdsh/releases/download/pdsh-2.34/pdsh-2.34.tar.gz
Source0  : https://github.com/chaos/pdsh/releases/download/pdsh-2.34/pdsh-2.34.tar.gz
Summary  : Parallel remote shell program
Group    : Development/Tools
License  : GPL-2.0
Requires: pdsh-bin = %{version}-%{release}
Requires: pdsh-lib = %{version}-%{release}
Requires: pdsh-license = %{version}-%{release}
Requires: pdsh-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : munge-dev
BuildRequires : ncurses-dev
BuildRequires : readline-dev
BuildRequires : slurm-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Pdsh is a multithreaded remote shell client which executes commands
on multiple remote hosts in parallel.  Pdsh can use several different
remote shell services, including standard "rsh", Kerberos IV, and ssh.

%package bin
Summary: bin components for the pdsh package.
Group: Binaries
Requires: pdsh-license = %{version}-%{release}

%description bin
bin components for the pdsh package.


%package lib
Summary: lib components for the pdsh package.
Group: Libraries
Requires: pdsh-license = %{version}-%{release}

%description lib
lib components for the pdsh package.


%package license
Summary: license components for the pdsh package.
Group: Default

%description license
license components for the pdsh package.


%package man
Summary: man components for the pdsh package.
Group: Default

%description man
man components for the pdsh package.


%prep
%setup -q -n pdsh-2.34
cd %{_builddir}/pdsh-2.34

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689832023
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static --with-slurm \
--without-rsh \
--with-readline \
--with-ssh \
--with-exec \
--with-mrsh \
--with-rcmd-rank-list="ssh mrsh exec"
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1689832023
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pdsh
cp %{_builddir}/pdsh-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pdsh/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dshbak
/usr/bin/pdcp
/usr/bin/pdsh
/usr/bin/rpdcp

%files lib
%defattr(-,root,root,-)
/usr/lib64/pdsh/execcmd.so
/usr/lib64/pdsh/mcmd.so
/usr/lib64/pdsh/slurm.so
/usr/lib64/pdsh/sshcmd.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pdsh/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dshbak.1
/usr/share/man/man1/pdcp.1
/usr/share/man/man1/pdsh.1
/usr/share/man/man1/rpdcp.1
