#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: 2659038
#
Name     : pdsh
Version  : 2.35
Release  : 12
URL      : https://github.com/chaos/pdsh/releases/download/pdsh-2.35/pdsh-2.35.tar.gz
Source0  : https://github.com/chaos/pdsh/releases/download/pdsh-2.35/pdsh-2.35.tar.gz
Summary  : Parallel remote shell program
Group    : Development/Tools
License  : GPL-2.0
Requires: pdsh-bin = %{version}-%{release}
Requires: pdsh-lib = %{version}-%{release}
Requires: pdsh-license = %{version}-%{release}
Requires: pdsh-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : munge-dev
BuildRequires : ncurses-dev
BuildRequires : readline-dev
BuildRequires : slurm-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Pdsh is a multithreaded remote shell client which executes commands
on multiple remote hosts in parallel.  Pdsh can use several different
remote shell services, including standard "rsh", Kerberos IV, and ssh.

%package bin
Summary: bin components for the pdsh package.
Group: Binaries
Requires: pdsh-license = %{version}-%{release}

%description bin
bin components for the pdsh package.


%package lib
Summary: lib components for the pdsh package.
Group: Libraries
Requires: pdsh-license = %{version}-%{release}

%description lib
lib components for the pdsh package.


%package license
Summary: license components for the pdsh package.
Group: Default

%description license
license components for the pdsh package.


%package man
Summary: man components for the pdsh package.
Group: Default

%description man
man components for the pdsh package.


%prep
%setup -q -n pdsh-2.35
cd %{_builddir}/pdsh-2.35
pushd ..
cp -a pdsh-2.35 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720111205
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-slurm \
--without-rsh \
--with-readline \
--with-ssh \
--with-exec \
--with-mrsh \
--with-rcmd-rank-list="ssh mrsh exec"
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-slurm \
--without-rsh \
--with-readline \
--with-ssh \
--with-exec \
--with-mrsh \
--with-rcmd-rank-list="ssh mrsh exec"
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720111205
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pdsh
cp %{_builddir}/pdsh-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pdsh/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pdcp
/V3/usr/bin/pdsh
/V3/usr/bin/rpdcp
/usr/bin/dshbak
/usr/bin/pdcp
/usr/bin/pdsh
/usr/bin/rpdcp

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/pdsh/execcmd.so
/V3/usr/lib64/pdsh/mcmd.so
/V3/usr/lib64/pdsh/slurm.so
/V3/usr/lib64/pdsh/sshcmd.so
/usr/lib64/pdsh/execcmd.so
/usr/lib64/pdsh/mcmd.so
/usr/lib64/pdsh/slurm.so
/usr/lib64/pdsh/sshcmd.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pdsh/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dshbak.1
/usr/share/man/man1/pdcp.1
/usr/share/man/man1/pdsh.1
/usr/share/man/man1/rpdcp.1
